# Makefile - Atmel SAMG5 MCU series
#
# Copyright (c) 2017 Microchip Technology Inc
#
# SPDX-License-Identifier: Apache-2.0
#

ZEPHYRINCLUDE += -I$(srctree)/arch/arm/soc/atmel_sam/common

obj-y += soc.o
